### ISSUE TITLE
blank screen on MOD Workspace

### ISSUE THREAD

**Issue by bernardoaraujor** [portalmod/mod-iso#10]
I plugged the Live USB on my ASUS U500V. I also have a M-Track Plus USB Audio Interface, which is plugged in.

MOD Workspace looks like this: 
![image](https://user-images.githubusercontent.com/9698228/31047051-166baefc-a5da-11e7-84f8-95e16cfdc1ee.png)

Is that how it's supposed to look?

Also, terminal has the following message:
```
bash: /usr/bin/groups: Input/output error
```

Here's the last portion of a dmesg:

![image](https://user-images.githubusercontent.com/9698228/31047059-32ff9cd6-a5da-11e7-818d-20a980f51b66.png)

**Comment by bernardoaraujor** [comment]
also, it takes an incredibly long time in the loading screen

**Comment by odurc** [comment]
It seems like is a filesystem issue. I'd try to flash the USB stick again.

**Comment by bernardoaraujor** [comment]
(fala crudo, beleza?)

Indeed, I flashed it again and now it worked.
But its still weird, cause before flashing it again, it worked fine on a different pc.

Anyways, thanks a lot!
